"""empty message

Revision ID: 07388bbd6306
Revises: 
Create Date: 2018-03-10 23:17:21.486629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07388bbd6306'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Stock',
    sa.Column('Ticker', sa.String(length=255), nullable=False),
    sa.Column('Date', sa.DateTime(), nullable=True),
    sa.Column('Open', sa.Float(), nullable=True),
    sa.Column('High', sa.Float(), nullable=True),
    sa.Column('Low', sa.Float(), nullable=True),
    sa.Column('Close', sa.Float(), nullable=True),
    sa.Column('Volume', sa.Float(), nullable=True),
    sa.Column('ExDividend', sa.Float(), nullable=True),
    sa.Column('SplitRatio', sa.Float(), nullable=True),
    sa.Column('AdjOpen', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('Ticker')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Stock')
    # ### end Alembic commands ###
