"""empty message

Revision ID: 1aa21dbe4028
Revises: 3d722634ceab
Create Date: 2018-03-19 15:19:43.908835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aa21dbe4028'
down_revision = '3d722634ceab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
