"""empty message

Revision ID: 3347520248b0
Revises: 1aa21dbe4028
Create Date: 2018-03-19 15:20:11.353340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3347520248b0'
down_revision = '1aa21dbe4028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
