"""empty message

Revision ID: 3d722634ceab
Revises: 7b4543791e47
Create Date: 2018-03-19 15:19:26.796846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d722634ceab'
down_revision = '7b4543791e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
