"""empty message

Revision ID: 70c0b9dfc6e8
Revises: 
Create Date: 2018-03-24 20:22:54.832125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70c0b9dfc6e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Stock',
    sa.Column('stockId', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('ex_dividend', sa.Float(), nullable=True),
    sa.Column('split_ratio', sa.Float(), nullable=True),
    sa.Column('adj_open', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('stockId')
    )
    op.create_table('users',
    sa.Column('userId', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_ticker', sa.String(length=255), nullable=True),
    sa.Column('userId', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlists')
    op.drop_table('users')
    op.drop_table('Stock')
    # ### end Alembic commands ###
