"""empty message

Revision ID: 79395d5f9e5b
Revises: 
Create Date: 2018-03-10 22:31:45.580493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79395d5f9e5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Date', sa.DateTime(), nullable=True),
    sa.Column('Ticker', sa.String(length=255), nullable=True),
    sa.Column('Open', sa.Float(), nullable=True),
    sa.Column('High', sa.Float(), nullable=True),
    sa.Column('Low', sa.Float(), nullable=True),
    sa.Column('Close', sa.Float(), nullable=True),
    sa.Column('Volume', sa.Float(), nullable=True),
    sa.Column('ExDividend', sa.Float(), nullable=True),
    sa.Column('SplitRatio', sa.Float(), nullable=True),
    sa.Column('AdjOpen', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stocks')
    # ### end Alembic commands ###
