"""empty message

Revision ID: a1c21813da79
Revises: ad93bf7c4e2d
Create Date: 2018-03-19 15:49:13.970310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1c21813da79'
down_revision = 'ad93bf7c4e2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
