"""empty message

Revision ID: ad93bf7c4e2d
Revises: 3347520248b0
Create Date: 2018-03-19 15:23:26.390447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad93bf7c4e2d'
down_revision = '3347520248b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
