"""empty message

Revision ID: f95cb0262784
Revises: 
Create Date: 2018-03-19 15:17:59.602076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f95cb0262784'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('accessToken', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('accessToken')
    )
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_ticker', sa.String(length=255), nullable=True),
    sa.Column('accessToken', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['accessToken'], ['users.accessToken'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlists')
    op.drop_table('users')
    # ### end Alembic commands ###
