TERM_EQUITY = "In accounting, equity is the difference between the value of the assets and the value of the liabilities of something owned."
TERM_PE_RATIO = "Price Earnings Ratio is a valuation of companies last traded share price to its latest reported 12 months earnings per share. For example, if the last traded share price of any X company is INR 40 and earnings over a last 12 months per share is INR 2, then the P/E ratio of that X company is INR 20 (40/2) "
TERM_MARKET_CAP = "Market Capitalization is the total value in INR of all of a company’s outstanding shares. It is calculated by multiplying all the outstanding shares with the current market price of one share. It determines the company’s size in terms of its wealth."

TERM_IPO = "Initial public offering or stock market launch is a type of public offering in which shares of a company are sold to institutional investors and usually also retail investors."
TERM_ASK = "The lowest price a seller is willing to accept when selling a stock."
TERM_BID = "The highest price a buyer is willing to accept when purchasing a stock."
TERM_BULL_MARKET = "When most stock prices are rising over several months."
TERM_BEAR_MARKET = "When most stock prices are falling our several months."
TERM_BROKER = "A person that buys or sells an investment for you in exchange for a fee called commission."
TERM_DIVIDEND = "A portion of a company’s profits that is paid out to shareholders on a quarterly or annual basis. The Board of Directors of the company declares dividends. It is not mandatory to declare dividends on common stock even though the company is making good profits."
TERM_SPREAD = "The difference between Ask and Bid."
TERM_YIELD = "When a company pays a dividend the yield is the percentage of dividend over the stock price. In other words, if a stock is trading for $10 and pays a dividend of $0.50, the yield is 5%, because for every $10 you invest, you would receive 5% back annually being $0.50"
TERM_LIQUIDITY = "A liquid market is a market with many bids ansplitd offers, low spreads, and low volatility. In a liquid market, it is easy to execute a trade quickly and at a desirable price because there are numerous buyers and sellers."